/**
 * BKDiablo Bank & Stash Layout Specification
 * Autogenerated from bankexpansionlayouthd.json
 */
window.D2R_BANK_LAYOUT = {
  "origin": {
    "x": 91,
    "y": 235
  },
  "scale": 0.32653061224489793,
  "stackable_slots": [
    {
      "name": "wms",
      "itemCode": "wms",
      "x": 976,
      "y": 1194,
      "width": 98,
      "height": 98
    },
    {
      "name": "gcw",
      "itemCode": "gcw",
      "x": 99,
      "y": 1077,
      "width": 98,
      "height": 98
    },
    {
      "name": "gfw",
      "itemCode": "gfw",
      "x": 99,
      "y": 1177,
      "width": 98,
      "height": 98
    },
    {
      "name": "gsw",
      "itemCode": "gsw",
      "x": 99,
      "y": 1277,
      "width": 98,
      "height": 98
    },
    {
      "name": "glw",
      "itemCode": "glw",
      "x": 99,
      "y": 1377,
      "width": 98,
      "height": 98
    },
    {
      "name": "gpw",
      "itemCode": "gpw",
      "x": 99,
      "y": 1477,
      "width": 98,
      "height": 98
    },
    {
      "name": "gcg",
      "itemCode": "gcg",
      "x": 221,
      "y": 1077,
      "width": 98,
      "height": 98
    },
    {
      "name": "gfg",
      "itemCode": "gfg",
      "x": 221,
      "y": 1177,
      "width": 98,
      "height": 98
    },
    {
      "name": "gsg",
      "itemCode": "gsg",
      "x": 221,
      "y": 1277,
      "width": 98,
      "height": 98
    },
    {
      "name": "glg",
      "itemCode": "glg",
      "x": 221,
      "y": 1377,
      "width": 98,
      "height": 98
    },
    {
      "name": "gpg",
      "itemCode": "gpg",
      "x": 221,
      "y": 1477,
      "width": 98,
      "height": 98
    },
    {
      "name": "gcr",
      "itemCode": "gcr",
      "x": 343,
      "y": 1077,
      "width": 98,
      "height": 98
    },
    {
      "name": "gfr",
      "itemCode": "gfr",
      "x": 343,
      "y": 1177,
      "width": 98,
      "height": 98
    },
    {
      "name": "gsr",
      "itemCode": "gsr",
      "x": 343,
      "y": 1277,
      "width": 98,
      "height": 98
    },
    {
      "name": "glr",
      "itemCode": "glr",
      "x": 343,
      "y": 1377,
      "width": 98,
      "height": 98
    },
    {
      "name": "gpr",
      "itemCode": "gpr",
      "x": 343,
      "y": 1477,
      "width": 98,
      "height": 98
    },
    {
      "name": "gcy",
      "itemCode": "gcy",
      "x": 465,
      "y": 1077,
      "width": 98,
      "height": 98
    },
    {
      "name": "gfy",
      "itemCode": "gfy",
      "x": 465,
      "y": 1177,
      "width": 98,
      "height": 98
    },
    {
      "name": "gsy",
      "itemCode": "gsy",
      "x": 465,
      "y": 1277,
      "width": 98,
      "height": 98
    },
    {
      "name": "gly",
      "itemCode": "gly",
      "x": 465,
      "y": 1377,
      "width": 98,
      "height": 98
    },
    {
      "name": "gpy",
      "itemCode": "gpy",
      "x": 465,
      "y": 1477,
      "width": 98,
      "height": 98
    },
    {
      "name": "gcv",
      "itemCode": "gcv",
      "x": 587,
      "y": 1077,
      "width": 98,
      "height": 98
    },
    {
      "name": "gfv",
      "itemCode": "gfv",
      "x": 587,
      "y": 1177,
      "width": 98,
      "height": 98
    },
    {
      "name": "gsv",
      "itemCode": "gsv",
      "x": 587,
      "y": 1277,
      "width": 98,
      "height": 98
    },
    {
      "name": "gzv",
      "itemCode": "gzv",
      "x": 587,
      "y": 1377,
      "width": 98,
      "height": 98
    },
    {
      "name": "gpv",
      "itemCode": "gpv",
      "x": 587,
      "y": 1477,
      "width": 98,
      "height": 98
    },
    {
      "name": "gcb",
      "itemCode": "gcb",
      "x": 710,
      "y": 1077,
      "width": 98,
      "height": 98
    },
    {
      "name": "gfb",
      "itemCode": "gfb",
      "x": 710,
      "y": 1177,
      "width": 98,
      "height": 98
    },
    {
      "name": "gsb",
      "itemCode": "gsb",
      "x": 710,
      "y": 1277,
      "width": 98,
      "height": 98
    },
    {
      "name": "glb",
      "itemCode": "glb",
      "x": 710,
      "y": 1377,
      "width": 98,
      "height": 98
    },
    {
      "name": "gpb",
      "itemCode": "gpb",
      "x": 710,
      "y": 1477,
      "width": 98,
      "height": 98
    },
    {
      "name": "skc",
      "itemCode": "skc",
      "x": 831,
      "y": 1077,
      "width": 98,
      "height": 98
    },
    {
      "name": "skf",
      "itemCode": "skf",
      "x": 831,
      "y": 1177,
      "width": 98,
      "height": 98
    },
    {
      "name": "sku",
      "itemCode": "sku",
      "x": 831,
      "y": 1277,
      "width": 98,
      "height": 98
    },
    {
      "name": "skl",
      "itemCode": "skl",
      "x": 831,
      "y": 1377,
      "width": 98,
      "height": 98
    },
    {
      "name": "skz",
      "itemCode": "skz",
      "x": 831,
      "y": 1477,
      "width": 98,
      "height": 98
    },
    {
      "name": "gav",
      "itemCode": "gav",
      "x": 587,
      "y": 1577,
      "width": 98,
      "height": 98
    },
    {
      "name": "gaw",
      "itemCode": "gaw",
      "x": 99,
      "y": 1577,
      "width": 98,
      "height": 98
    },
    {
      "name": "gag",
      "itemCode": "gag",
      "x": 221,
      "y": 1577,
      "width": 98,
      "height": 98
    },
    {
      "name": "gar",
      "itemCode": "gar",
      "x": 343,
      "y": 1577,
      "width": 98,
      "height": 98
    },
    {
      "name": "gab",
      "itemCode": "gab",
      "x": 710,
      "y": 1577,
      "width": 98,
      "height": 98
    },
    {
      "name": "gay",
      "itemCode": "gay",
      "x": 465,
      "y": 1577,
      "width": 98,
      "height": 98
    },
    {
      "name": "ska",
      "itemCode": "ska",
      "x": 831,
      "y": 1577,
      "width": 98,
      "height": 98
    },
    {
      "name": "cct",
      "itemCode": "cct",
      "x": 1043,
      "y": 1339,
      "width": 98,
      "height": 98
    },
    {
      "name": "bct",
      "itemCode": "bct",
      "x": 1147,
      "y": 1339,
      "width": 98,
      "height": 98
    },
    {
      "name": "sct",
      "itemCode": "sct",
      "x": 1252,
      "y": 1339,
      "width": 98,
      "height": 98
    },
    {
      "name": "pct",
      "itemCode": "pct",
      "x": 1355,
      "y": 1339,
      "width": 98,
      "height": 98
    },
    {
      "name": "std",
      "itemCode": "std",
      "x": 1252,
      "y": 1445,
      "width": 98,
      "height": 98
    },
    {
      "name": "pk1",
      "itemCode": "pk1",
      "x": 100,
      "y": 583,
      "width": 98,
      "height": 196
    },
    {
      "name": "ua1",
      "itemCode": "ua1",
      "x": 411,
      "y": 583,
      "width": 98,
      "height": 196
    },
    {
      "name": "ua2",
      "itemCode": "ua2",
      "x": 515,
      "y": 583,
      "width": 98,
      "height": 196
    },
    {
      "name": "ua3",
      "itemCode": "ua3",
      "x": 621,
      "y": 583,
      "width": 98,
      "height": 196
    },
    {
      "name": "ua4",
      "itemCode": "ua4",
      "x": 725,
      "y": 583,
      "width": 98,
      "height": 196
    },
    {
      "name": "ua5",
      "itemCode": "ua5",
      "x": 829,
      "y": 583,
      "width": 98,
      "height": 196
    },
    {
      "name": "dhn",
      "itemCode": "dhn",
      "x": 99,
      "y": 811,
      "width": 98,
      "height": 98
    },
    {
      "name": "xa1",
      "itemCode": "xa1",
      "x": 412,
      "y": 811,
      "width": 98,
      "height": 98
    },
    {
      "name": "xa2",
      "itemCode": "xa2",
      "x": 516,
      "y": 811,
      "width": 98,
      "height": 98
    },
    {
      "name": "xa3",
      "itemCode": "xa3",
      "x": 620,
      "y": 811,
      "width": 98,
      "height": 98
    },
    {
      "name": "xa4",
      "itemCode": "xa4",
      "x": 725,
      "y": 811,
      "width": 98,
      "height": 98
    },
    {
      "name": "xa5",
      "itemCode": "xa5",
      "x": 828,
      "y": 811,
      "width": 98,
      "height": 98
    },
    {
      "name": "rvs",
      "itemCode": "rvs",
      "x": 99,
      "y": 950,
      "width": 98,
      "height": 98
    },
    {
      "name": "rvl",
      "itemCode": "rvl",
      "x": 202,
      "y": 950,
      "width": 98,
      "height": 98
    },
    {
      "name": "toa",
      "itemCode": "toa",
      "x": 412,
      "y": 950,
      "width": 98,
      "height": 98
    },
    {
      "name": "tes",
      "itemCode": "tes",
      "x": 517,
      "y": 950,
      "width": 98,
      "height": 98
    },
    {
      "name": "ceh",
      "itemCode": "ceh",
      "x": 621,
      "y": 950,
      "width": 98,
      "height": 98
    },
    {
      "name": "bet",
      "itemCode": "bet",
      "x": 724,
      "y": 950,
      "width": 98,
      "height": 98
    },
    {
      "name": "fed",
      "itemCode": "fed",
      "x": 828,
      "y": 950,
      "width": 98,
      "height": 98
    },
    {
      "name": "r01",
      "itemCode": "r01",
      "x": 99,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r02",
      "itemCode": "r02",
      "x": 203,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r03",
      "itemCode": "r03",
      "x": 307,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r04",
      "itemCode": "r04",
      "x": 411,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r05",
      "itemCode": "r05",
      "x": 515,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r06",
      "itemCode": "r06",
      "x": 620,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r07",
      "itemCode": "r07",
      "x": 723,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r08",
      "itemCode": "r08",
      "x": 827,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r09",
      "itemCode": "r09",
      "x": 931,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r10",
      "itemCode": "r10",
      "x": 1035,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r11",
      "itemCode": "r11",
      "x": 1139,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r12",
      "itemCode": "r12",
      "x": 1243,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r13",
      "itemCode": "r13",
      "x": 1347,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r14",
      "itemCode": "r14",
      "x": 1451,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r15",
      "itemCode": "r15",
      "x": 1555,
      "y": 242,
      "width": 98,
      "height": 98
    },
    {
      "name": "r16",
      "itemCode": "r16",
      "x": 99,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r17",
      "itemCode": "r17",
      "x": 203,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r18",
      "itemCode": "r18",
      "x": 307,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r19",
      "itemCode": "r19",
      "x": 411,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r20",
      "itemCode": "r20",
      "x": 515,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r21",
      "itemCode": "r21",
      "x": 619,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r22",
      "itemCode": "r22",
      "x": 723,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r23",
      "itemCode": "r23",
      "x": 827,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r24",
      "itemCode": "r24",
      "x": 931,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r25",
      "itemCode": "r25",
      "x": 1035,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r26",
      "itemCode": "r26",
      "x": 1139,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r27",
      "itemCode": "r27",
      "x": 1243,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r28",
      "itemCode": "r28",
      "x": 1347,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r29",
      "itemCode": "r29",
      "x": 1451,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r30",
      "itemCode": "r30",
      "x": 1555,
      "y": 347,
      "width": 98,
      "height": 98
    },
    {
      "name": "r31",
      "itemCode": "r31",
      "x": 99,
      "y": 450,
      "width": 98,
      "height": 98
    },
    {
      "name": "r32",
      "itemCode": "r32",
      "x": 203,
      "y": 452,
      "width": 98,
      "height": 98
    },
    {
      "name": "r33",
      "itemCode": "r33",
      "x": 307,
      "y": 450,
      "width": 98,
      "height": 98
    },
    {
      "name": "mfp",
      "itemCode": "mfp",
      "x": 1043,
      "y": 1446,
      "width": 98,
      "height": 98
    },
    {
      "name": "tds",
      "itemCode": "tds",
      "x": 1147,
      "y": 1446,
      "width": 98,
      "height": 98
    },
    {
      "name": "dsd",
      "itemCode": "dsd",
      "x": 1355,
      "y": 1446,
      "width": 98,
      "height": 98
    },
    {
      "name": "brk",
      "itemCode": "brk",
      "x": 307,
      "y": 811,
      "width": 98,
      "height": 98
    },
    {
      "name": "mbk",
      "itemCode": "mbk",
      "x": 307,
      "y": 949,
      "width": 98,
      "height": 98
    },
    {
      "name": "rrr",
      "itemCode": "rrr",
      "x": 1459,
      "y": 1341,
      "width": 98,
      "height": 98
    },
    {
      "name": "rtr",
      "itemCode": "rtr",
      "x": 1459,
      "y": 1446,
      "width": 98,
      "height": 98
    },
    {
      "name": "fel",
      "itemCode": "fel",
      "x": 1043,
      "y": 1549,
      "width": 98,
      "height": 98
    },
    {
      "name": "voa",
      "itemCode": "voa",
      "x": 1147,
      "y": 1549,
      "width": 98,
      "height": 98
    },
    {
      "name": "gwh",
      "itemCode": "gwh",
      "x": 1252,
      "y": 1549,
      "width": 98,
      "height": 98
    },
    {
      "name": "hsm",
      "itemCode": "hsm",
      "x": 1355,
      "y": 1549,
      "width": 98,
      "height": 98
    },
    {
      "name": "dss",
      "itemCode": "dss",
      "x": 1459,
      "y": 1549,
      "width": 98,
      "height": 98
    }
  ],
  "crafting_slots": [
    {
      "name": "mfp",
      "itemCode": "mfp",
      "x": 1043,
      "y": 1446,
      "width": 98,
      "height": 98
    },
    {
      "name": "tds",
      "itemCode": "tds",
      "x": 1147,
      "y": 1446,
      "width": 98,
      "height": 98
    },
    {
      "name": "dsd",
      "itemCode": "dsd",
      "x": 1355,
      "y": 1446,
      "width": 98,
      "height": 98
    },
    {
      "name": "std",
      "itemCode": "std",
      "x": 1252,
      "y": 1446,
      "width": 98,
      "height": 98
    },
    {
      "name": "rtr",
      "itemCode": "rtr",
      "x": 1459,
      "y": 1446,
      "width": 98,
      "height": 98
    },
    {
      "name": "fel",
      "itemCode": "fel",
      "x": 1043,
      "y": 1549,
      "width": 98,
      "height": 98
    },
    {
      "name": "voa",
      "itemCode": "voa",
      "x": 1147,
      "y": 1549,
      "width": 98,
      "height": 98
    },
    {
      "name": "gwh",
      "itemCode": "gwh",
      "x": 1252,
      "y": 1549,
      "width": 98,
      "height": 98
    },
    {
      "name": "hsm",
      "itemCode": "hsm",
      "x": 1355,
      "y": 1549,
      "width": 98,
      "height": 98
    },
    {
      "name": "dss",
      "itemCode": "dss",
      "x": 1459,
      "y": 1549,
      "width": 98,
      "height": 98
    },
    {
      "name": "cct",
      "itemCode": "cct",
      "x": 1043,
      "y": 1339,
      "width": 98,
      "height": 98
    },
    {
      "name": "bct",
      "itemCode": "bct",
      "x": 1147,
      "y": 1339,
      "width": 98,
      "height": 98
    },
    {
      "name": "sct",
      "itemCode": "sct",
      "x": 1252,
      "y": 1339,
      "width": 98,
      "height": 98
    },
    {
      "name": "pct",
      "itemCode": "pct",
      "x": 1355,
      "y": 1339,
      "width": 98,
      "height": 98
    },
    {
      "name": "rrr",
      "itemCode": "rrr",
      "x": 1459,
      "y": 1339,
      "width": 98,
      "height": 98
    },
    {
      "name": "mls",
      "itemCode": "mls",
      "x": 622,
      "y": 545,
      "width": 98,
      "height": 196
    },
    {
      "name": "lmr",
      "itemCode": "lmr",
      "x": 726,
      "y": 545,
      "width": 98,
      "height": 196
    },
    {
      "name": "bgn",
      "itemCode": "bgn",
      "x": 830,
      "y": 545,
      "width": 98,
      "height": 196
    },
    {
      "name": "gft",
      "itemCode": "gft",
      "x": 721,
      "y": 845,
      "width": 98,
      "height": 196
    },
    {
      "name": "dw1",
      "itemCode": "dw1",
      "x": 726,
      "y": 1144,
      "width": 98,
      "height": 98
    },
    {
      "name": "db1",
      "itemCode": "db1",
      "x": 726,
      "y": 1244,
      "width": 98,
      "height": 98
    },
    {
      "name": "1dr",
      "itemCode": "1dr",
      "x": 726,
      "y": 1344,
      "width": 98,
      "height": 98
    }
  ],
  "crafting_cube": {
    "x": 1002,
    "y": 538,
    "cellCount": {
      "x": 6,
      "y": 6
    }
  },
  "crafting_buttons": [
    {
      "name": "convert",
      "type": "ButtonWidget",
      "x": 1239,
      "y": 1158,
      "text": "TRANSMUTE"
    },
    {
      "name": "withdraw_button",
      "type": "ButtonWidget",
      "x": 1154,
      "y": 1158,
      "text": "Withdraw"
    }
  ]
};
